pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'git@github.com:Invesgood/jenkins.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    dockerImage = docker.build("my-static-web:${env.BUILD_NUMBER}")
                }
            }
        }

        stage('Stop Previous Container') {
            steps {
                script {
                    sh 'docker stop my-static-web || true'
                    sh 'docker rm my-static-web || true'
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    sh "docker run -d -p 8088:80 --name my-static-web my-static-web:${env.BUILD_NUMBER}"
                }
            }
        }

        stage('Clean Up Old Images') {
            steps {
                script {
                    sh 'docker image prune -f'
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline completed!'
        }
        success {
            echo 'Deployment successful! Web app is running on port 8080'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}